env:
  REACT_APP_API_URL: 'https://vljrc1aep0.execute-api.ap-southeast-1.amazonaws.com/uat/f/api/v1/scheduler/'
  REACT_APP_X_API_KEY: 'bLm8c1C0fL3FtPzrjSr0'
 
# This is a basic workflow to help you get started with Actions
name: scheduler-company-f-ui-auto-deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ deploy ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.9.1]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.10.0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          node-version: ${{ matrix.node-version }}
      - name: Build React App
        run: npm install && npm run build
        env:
         CI: false
         NODE_OPTIONS: "--max_old_space_size=4096"
      - name: Deploy app build to S3 bucket
        run: aws s3 sync ./build/ s3://${{ secrets.S3_BUCKET }} --delete
